# Site settings
title: Style guide template
email: jerome.coupe@webstoemp.com
description: Style guide boilerplate with Jekyll
baseurl: ""
url: "http://www.webstoemp.com/jekyllstyleguide" # the base hostname & protocol for your site
twitter_username: jeromecoupe
github_username:  jeromecoupe

# Collections
collections:
  components:
    output: false

# Front Matter Defaults

# General settings
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed
