# Site settings
title: HFC Relay - Frontend Framework
description: HFC prototyping Framework
baseurl: ""
url: ""
github_repo: https://github.com/NilsDannemann/j_hfc_relay/blob/gh-pages

# Generate ".deploy" folder on build
destination: .deploy
exclude: [node_modules, Gulpfile.js, package.json, README.md]

# Collections
collections:
  components:
    output: false

# Include
include: ['_pages']

# General settings
port: 3000
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _includes
  style: compressed