# Site settings
title: HFC Relay - Frontend Framework
description: HFC prototyping Framework
github_repo: https://github.com/NilsDannemann/j_hfc_relay

# Generate ".deploy" folder on build
destination: .deploy
exclude: ['node_modules', 'Gulpfile.js', 'package.json', 'README.md', '*.sublime-project', '*.sublime-workspace']

# Collections
collections:
  components:
    output: false

# Include
include: ['_pages']

# General settings
port: 3000
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _includes
  style: compressed