# Site settings
title: HFC Relay - Frontend Framework
description: Extremely efficient prototyping
baseurl: "/j_hfc_relay"
url: ""
github_repo: https://github.com/NilsDannemann/j_hfc_relay/blob/gh-pages

# Collections
collections:
  components:
    output: false

# Pages
include: ['_pages']

# General settings
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _includes
  style: compressed

# Scripts
use_jquery: 	 true
# Icon Sets
use_fontawesome: true
use_ionicons: 	 false
# Components
use_components: 
  breadcrumb: 	true
  button: 		true
  teaser: 		true
